name: JS Actions

on:
  pull_request:
    types: [labeled]

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: hello-action
        uses: ./.github/actions/hello-world
        with:
          first-greeting: "Spock"
          third-greeting: "Bones"
      - name: tell-joke-action
        uses: ./.github/actions/joke-action
